# Generated by Django 5.0.3 on 2024-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="_default_address",
            field=models.BooleanField(default=False),
        ),
    ]
