# Generated by Django 5.0.3 on 2024-05-22 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_deliveryagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryagent",
            name="location",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
